(function(){
'use strict';var g,aa=Object.freeze({esVersion:6,assumingES6:!0,isWebAssembly:!1,productionMode:!0,linkerVersion:"1.17.0",fileLevelThis:this}),ba;function k(a){this.Ra=a}k.prototype.toString=function(){return String.fromCharCode(this.Ra)};
function ca(a){switch(typeof a){case "string":return m(da);case "number":return ea(a)?a<<24>>24===a?m(fa):a<<16>>16===a?m(ha):m(ia):ja(a)?m(ka):m(la);case "boolean":return m(ma);case "undefined":return m(na);default:return null===a?a.Vc():a instanceof n?m(oa):a instanceof k?m(pa):a&&a.$classData?m(a.$classData):null}}
function qa(a){switch(typeof a){case "string":return"java.lang.String";case "number":return ea(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":ja(a)?"java.lang.Float":"java.lang.Double";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Vc():a instanceof n?"java.lang.Long":a instanceof k?"java.lang.Character":a&&a.$classData?a.$classData.name:null.Bd()}}
function ra(a){switch(typeof a){case "string":return sa(a);case "number":return ta(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.fa():a instanceof n?a.W^a.V:a instanceof k?null===a?0:a.Ra:ua.prototype.fa.call(a)}}function wa(a){return void 0===a?"undefined":a.toString()}function xa(a,b,c,d,e){if(a!==c||d<b||(b+e|0)<d)for(var f=0;f<e;f=f+1|0)c[d+f|0]=a[b+f|0];else for(f=e-1|0;0<=f;f=f-1|0)c[d+f|0]=a[b+f|0]}var ya=0,za=new WeakMap;
function Aa(a){switch(typeof a){case "string":return sa(a);case "number":return ta(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:sa(a);default:if(null===a)return 0;b=za.get(a);void 0===b&&(ya=b=ya+1|0,za.set(a,b));return b}}function ea(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}
function ja(a){return"number"===typeof a&&(a!==a||Math.fround(a)===a)}function ua(){}ua.prototype.constructor=ua;function p(){}p.prototype=ua.prototype;ua.prototype.fa=function(){return Aa(this)};ua.prototype.C=function(){var a=this.fa();return qa(this)+"@"+(+(a>>>0)).toString(16)};ua.prototype.toString=function(){return this.C()};function r(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}r.prototype=new p;r.prototype.constructor=r;
r.prototype.f=function(a,b,c,d){xa(this.a,a,b.a,c,d)};function Ba(){}Ba.prototype=r.prototype;function t(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}t.prototype=new p;t.prototype.constructor=t;t.prototype.f=function(a,b,c,d){xa(this.a,a,b.a,c,d)};function y(a){this.a="number"===typeof a?new Uint16Array(a):a}y.prototype=new p;y.prototype.constructor=y;y.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};
function z(a){this.a="number"===typeof a?new Int8Array(a):a}z.prototype=new p;z.prototype.constructor=z;z.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};function B(a){this.a="number"===typeof a?new Int16Array(a):a}B.prototype=new p;B.prototype.constructor=B;B.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};function D(a){this.a="number"===typeof a?new Int32Array(a):a}D.prototype=new p;D.prototype.constructor=D;
D.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};function E(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=ba}else this.a=a}E.prototype=new p;E.prototype.constructor=E;E.prototype.f=function(a,b,c,d){xa(this.a,a,b.a,c,d)};function F(a){this.a="number"===typeof a?new Float32Array(a):a}F.prototype=new p;F.prototype.constructor=F;F.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};
function G(a){this.a="number"===typeof a?new Float64Array(a):a}G.prototype=new p;G.prototype.constructor=G;G.prototype.f=function(a,b,c,d){b.a.set(this.a.subarray(a,a+d|0),c)};function Ca(){this.m=void 0;this.Ba=this.Sa=this.Q=null;this.Ca=0;this.Rc=null;this.na="";this.oa=this.Aa=this.Db=void 0;this.name="";this.Gb=this.gc=this.Xa=!1;this.Ea=void 0}function Da(a,b,c,d){var e=new Ca;e.Q={};e.Rc=a;e.na=b;e.oa=f=>f===e;e.name=c;e.Xa=!0;e.Ea=()=>!1;void 0!==d&&(e.Aa=Ea(e,d));return e}
function H(a,b,c,d){var e=new Ca,f=Object.getOwnPropertyNames(c)[0];e.Q=c;e.na="L"+b+";";e.oa=h=>!!h.Q[f];e.name=b;e.gc=1===a;e.Ea=d||(h=>!!(h&&h.$classData&&h.$classData.Q[f]));"number"!==typeof a&&(a.prototype.$classData=e);return e}function Ea(a,b,c){var d=new Ca;b.prototype.$classData=d;var e="["+a.na;d.m=b;d.Q={Za:1,c:1};d.Sa=a;d.Ba=a;d.Ca=1;d.na=e;d.name=e;d.Gb=!0;d.oa=c||(f=>d===f);d.Ea=f=>f instanceof b;return d}
function Fa(a){function b(l){if("number"===typeof l){this.a=Array(l);for(var q=0;q<l;q++)this.a[q]=null}else this.a=l}var c=new Ca;b.prototype=new Ba;b.prototype.constructor=b;b.prototype.f=function(l,q,w,A){xa(this.a,l,q.a,w,A)};b.prototype.$classData=c;var d=a.Ba||a,e=a.Ca+1,f="["+a.na;c.m=b;c.Q={Za:1,c:1};c.Sa=a;c.Ba=d;c.Ca=e;c.na=f;c.name=f;c.Gb=!0;var h=l=>{var q=l.Ca;return q===e?d.oa(l.Ba):q>e&&d===I};c.oa=h;c.Ea=l=>{l=l&&l.$classData;return!!l&&(l===c||h(l))};return c}
function J(a){a.Aa||(a.Aa=Fa(a));return a.Aa}function m(a){a.Db||(a.Db=new Ga(a));return a.Db}function Ha(a){return a.Sa?m(a.Sa):null}function Ia(a,b){if(a===Ja)throw a=new Ka,K(a,null),a;return new (J(a).m)(b)}var I=new Ca;I.Q={};I.na="Ljava.lang.Object;";I.oa=a=>!a.Xa;I.name="java.lang.Object";I.Ea=a=>null!==a;I.Aa=Ea(I,r,a=>{var b=a.Ca;return 1===b?!a.Ba.Xa:1<b});ua.prototype.$classData=I;var Ja=Da(void 0,"V","void",void 0);Da(!1,"Z","boolean",t);Da(0,"C","char",y);Da(0,"B","byte",z);
Da(0,"S","short",B);Da(0,"I","int",D);var La=Da(null,"J","long",E);Da(0,"F","float",F);Da(0,"D","double",G);function Ma(){this.ec=this.za=null;Na=this;this.za=require("fs");require("path");this.ec=process}Ma.prototype=new p;Ma.prototype.constructor=Ma;function Oa(a,b){return wa(L().za.readFileSync(b))}function Qa(){L();L().ec.exit(1);var a=new N;K(a,"Unreachable code after process.exit");throw a;}H(Ma,"io.github.edadma.cross_platform.package$package$",{ud:1});var Na;
function L(){Na||(Na=new Ma);return Na}function Ra(){}Ra.prototype=new p;Ra.prototype.constructor=Ra;H(Ra,"io.github.edadma.files.Main$package$",{vd:1});var Sa;function Ta(){this.jc=this.$a=this.Fa=null;Ua=this;this.Fa=new ArrayBuffer(8);this.$a=new Int32Array(this.Fa,0,2);new Float32Array(this.Fa,0,2);this.jc=new Float64Array(this.Fa,0,1);this.$a[0]=16909060;new Int8Array(this.Fa,0,8)}Ta.prototype=new p;Ta.prototype.constructor=Ta;
function Va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.jc[0]=b;return(a.$a[0]|0)^(a.$a[1]|0)}H(Ta,"java.lang.FloatingPointBits$",{Kd:1});var Ua;function Wa(){Ua||(Ua=new Ta);return Ua}function Xa(){this.kc=this.lc=null;Ya=this;this.lc=new Za(!1);this.kc=new Za(!0)}Xa.prototype=new p;Xa.prototype.constructor=Xa;H(Xa,"java.lang.System$Streams$",{Wd:1});var Ya;function $a(){Ya||(Ya=new Xa);return Ya}
function ab(){this.mc=this.Hb=null;bb=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Hb=a;this.mc=null}ab.prototype=new p;ab.prototype.constructor=ab;function cb(a,b,c){return null!==a.Hb?(a=a.Hb,db||(db=new eb),db.oc.call(a,b)?a[b]:c):cb(a.mc,b,c)}H(ab,"java.lang.System$SystemProperties$",{Xd:1});var bb;function eb(){this.oc=null;db=this;this.oc=Object.prototype.hasOwnProperty}eb.prototype=new p;eb.prototype.constructor=eb;H(eb,"java.lang.Utils$Cache$",{Zd:1});var db,na=H(0,"java.lang.Void",{$d:1},a=>void 0===a);function fb(){}fb.prototype=new p;
fb.prototype.constructor=fb;function gb(a,b){if(b instanceof r)a=b.a.length;else if(b instanceof t)a=b.a.length;else if(b instanceof y)a=b.a.length;else if(b instanceof z)a=b.a.length;else if(b instanceof B)a=b.a.length;else if(b instanceof D)a=b.a.length;else if(b instanceof E)a=b.a.length;else if(b instanceof F)a=b.a.length;else if(b instanceof G)a=b.a.length;else throw hb("argument type mismatch");return a}H(fb,"java.lang.reflect.Array$",{ae:1});var ib;function jb(){ib||(ib=new fb);return ib}
function kb(){}kb.prototype=new p;kb.prototype.constructor=kb;function O(a,b,c){if(0>c)throw new lb;a=b.a.length;a=c<a?c:a;c=Ia(Ha(ca(b).D).D,c);b.f(0,c,0,a);return c}function P(a,b,c,d){if(c>d)throw hb(c+" \x3e "+d);a=d-c|0;d=b.a.length-c|0;d=a<d?a:d;a=Ia(Ha(ca(b).D).D,a);b.f(c,a,0,d);return a}H(kb,"java.util.Arrays$",{be:1});var mb;function Q(){mb||(mb=new kb);return mb}function n(a,b){this.W=a;this.V=b}n.prototype=new p;n.prototype.constructor=n;n.prototype.fa=function(){return this.W^this.V};
n.prototype.C=function(){nb();var a=this.W,b=this.V;return b===a>>31?""+a:0>b?"-"+ob(-a|0,0!==a?~b:-b|0):ob(a,b)};H(n,"org.scalajs.linker.runtime.RuntimeLong",{yd:1});
function ob(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+(Math.clz32(1E9)|0)|0)-(0!==b?Math.clz32(b)|0:32+(Math.clz32(a)|0)|0)|0,d=c,e=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var f=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var l=f,q=h,w=e,A=d;if(q===A?(-2147483648^l)>=(-2147483648^w):(-2147483648^q)>=(-2147483648^A))l=h,q=d,h=f-e|0,l=(-2147483648^h)>(-2147483648^f)?-1+(l-q|0)|0:l-q|0,f=h,h=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;e=e>>>1|0|d<<31;d=l}c=
h;if(0===c?-1147483648<=(-2147483648^f):-2147483648<=(-2147483648^c))c=4294967296*h+ +(f>>>0),f=c/1E9,e=f/4294967296|0,d=b,b=f=d+(f|0)|0,a=(-2147483648^f)<(-2147483648^d)?1+(a+e|0)|0:a+e|0,f=c%1E9|0;c=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function pb(){this.Qa=0}pb.prototype=new p;pb.prototype.constructor=pb;H(pb,"org.scalajs.linker.runtime.RuntimeLong$",{zd:1});var qb;function nb(){qb||(qb=new pb);return qb}
function rb(a,b,c,d){a=a.B();var e=c,f=gb(jb(),b)-c|0;for(d=c+(d<f?d:f)|0;e<d&&a.A();)sb(tb(),b,e,a.v()),e=1+e|0;return e-c|0}function ub(a,b,c,d,e){var f=b.E;0!==c.length&&(f.o=""+f.o+c);a=a.B();if(a.A())for(c=a.v(),f.o=""+f.o+c;a.A();)f.o=""+f.o+d,c=a.v(),f.o=""+f.o+c;0!==e.length&&(f.o=""+f.o+e);return b}function vb(){wb=this}vb.prototype=new p;vb.prototype.constructor=vb;function xb(a,b,c){b=0<b?b:0;var d=a.length;c=c<d?c:d;return b>=c?"":a.substring(b,c)}
function yb(a,b){var c=b.length;a=new zb;Cb(a);if(0>c)throw new lb;for(b=new Db(b,!1);b.t<b.pa;){c=Eb(b);for(var d=c.length,e=0;e<d&&32>=c.charCodeAt(e);)e=1+e|0;c=e<d&&124===c.charCodeAt(e)?c.substring(1+e|0):c;a.o=""+a.o+c}return a.o}function Fb(){R();var a=S;R();var b=a.length;return xb(a,1<b?1:b,a.length)}H(vb,"scala.collection.StringOps$",{ye:1});var wb;function R(){wb||(wb=new vb);return wb}
function Gb(){this.cc=null;Hb=this;this.cc=new r(0);new (J(J(I)).m)(0);new (J(J(J(I))).m)(0);new (J(J(J(J(I)))).m)(0);new (J(J(J(J(J(I))))).m)(0);new (J(J(J(J(J(J(I)))))).m)(0)}Gb.prototype=new p;Gb.prototype.constructor=Gb;function Ib(a,b,c){a=Ia(Ha(ca(c).D).D,1+c.a.length|0);c.f(0,a,1,c.a.length);a.a[0]=b;return a}function Jb(a,b,c,d){var e=0,f=c.a.length;if(0===b)for(;e<f;)d.G(c.a[e]),e=1+e|0;else for(b=-1+b|0;e<f;)Jb(a,b,c.a[e],d),e=1+e|0}H(Gb,"scala.collection.immutable.VectorStatics$",{Oe:1});
var Hb;function T(){Hb||(Hb=new Gb);return Hb}function Kb(){}Kb.prototype=new p;Kb.prototype.constructor=Kb;
function sb(a,b,c,d){if(b instanceof r)b.a[c]=d;else if(b instanceof D)b.a[c]=d|0;else if(b instanceof G)b.a[c]=+d;else if(b instanceof E)b.a[c]=null===d?ba:d;else if(b instanceof F)b.a[c]=Math.fround(d);else if(b instanceof y)b.a[c]=null===d?0:d.Ra;else if(b instanceof z)b.a[c]=d|0;else if(b instanceof B)b.a[c]=d|0;else if(b instanceof t)b.a[c]=!!d;else{if(null===b)throw new Lb;throw new U(b);}}H(Kb,"scala.runtime.ScalaRunTime$",{$e:1});var Mb;function tb(){Mb||(Mb=new Kb);return Mb}
function Nb(){}Nb.prototype=new p;Nb.prototype.constructor=Nb;
function V(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=nb();if(-0x7fffffffffffffff>a){b.Qa=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.Qa=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.Qa=0>a&&0!==c?-1+d|0:d}b=b.Qa;nb();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:Va(Wa(),a)}return a}return b instanceof n?(a=null===b?ba:b,b=new n(a.W,a.V),a=b.W,b=b.V,b===
a>>31?a:a^b):ra(b)}H(Nb,"scala.runtime.Statics$",{af:1});var Ob;function W(){Ob||(Ob=new Nb);return Ob}function Pb(){}Pb.prototype=new p;Pb.prototype.constructor=Pb;function Qb(a,b,c,d){return c<b.a.length?new Rb(b.a[c],Qb(a,b,1+c|0,d)):Sb()}H(Pb,"scala.util.CommandLineParser$",{he:1});var Tb;function Ub(){Tb||(Tb=new Pb);return Tb}function Vb(a){this.Nb=a}Vb.prototype=new p;Vb.prototype.constructor=Vb;Vb.prototype.C=function(){return"DynamicVariable("+this.Nb+")"};
H(Vb,"scala.util.DynamicVariable",{le:1});function Wb(){}Wb.prototype=new p;Wb.prototype.constructor=Wb;function Xb(){}Xb.prototype=Wb.prototype;function X(a,b){a=Yb(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Yb(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function Y(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function Zb(a){0===(32&a.Ya)<<24>>24&&0===(32&a.Ya)<<24>>24&&(a.ic=new D(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3558,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43504,43600,44016,65296,66720,68912,69734,69872,69942,70096,70384,70736,70864,71248,71360,71472,71904,72016,72784,73040,73120,73552,92768,92864,93008,120782,120792,120802,120812,120822,123200,123632,124144,125264,130032])),a.Ya=(32|a.Ya)<<24>>24);return a.ic}
function $b(){this.ic=null;this.Ya=0}$b.prototype=new p;$b.prototype.constructor=$b;H($b,"java.lang.Character$",{Gd:1,c:1});var ac;function bc(a){throw new fc('For input string: "'+a+'"');}function gc(){}gc.prototype=new p;gc.prototype.constructor=gc;H(gc,"java.lang.Integer$",{Nd:1,c:1});var hc;function K(a,b){a.nc=b;"[object Error]"!==Object.prototype.toString.call(a instanceof ic?a.dc:a)&&(void 0===Error.captureStackTrace||Object.isSealed(a)?Error():Error.captureStackTrace(a))}
class jc extends Error{constructor(){super();this.nc=null}Va(){return this.nc}C(){var a=qa(this),b=this.Va();return null===b?a:a+": "+b}fa(){return ua.prototype.fa.call(this)}get message(){var a=this.Va();return null===a?"":a}get name(){return qa(this)}toString(){return this.C()}}function kc(){}kc.prototype=new p;kc.prototype.constructor=kc;H(kc,"scala.Array$",{de:1,c:1});var lc;function mc(){this.pc=this.qc=null;nc=this;this.qc=new Vb($a().lc);this.pc=new Vb($a().kc)}mc.prototype=new p;
mc.prototype.constructor=mc;function oc(){return pc().qc.Nb}H(mc,"scala.Console$",{ee:1,ge:1});var nc;function pc(){nc||(nc=new mc);return nc}function qc(a,b){if(b===a){var c=a.Eb;rc||(rc=new sc);c.call(a,rc.Ua(b))}else for(b=b.B();b.A();)a.Fb(b.v());return a}function tc(){}tc.prototype=new p;tc.prototype.constructor=tc;function uc(){}uc.prototype=tc.prototype;tc.prototype.C=function(){return"\x3cfunction1\x3e"};function vc(){}vc.prototype=new p;vc.prototype.constructor=vc;
H(vc,"scala.util.CommandLineParser$FromString$given_FromString_String$",{je:1,ie:1});var wc;function xc(){this.tc=this.eb=0;yc=this;this.eb=sa("Seq");this.tc=sa("Map");sa("Set");var a=Sb(),b=this.tc,c=0,d=0,e=0,f=1;for(a=a.B();a.A();){var h=a.v();h=V(W(),h);c=c+h|0;d^=h;f=Math.imul(f,1|h);e=1+e|0}b=X(b,c);b=X(b,d);b=Yb(b,f);Y(b^e)}xc.prototype=new Xb;xc.prototype.constructor=xc;H(xc,"scala.util.hashing.MurmurHash3$",{ne:1,me:1});var yc;function zc(){yc||(yc=new xc);return yc}
function Ga(a){this.D=a}Ga.prototype=new p;Ga.prototype.constructor=Ga;Ga.prototype.C=function(){return(this.D.gc?"interface ":this.D.Xa?"":"class ")+this.D.name};H(Ga,"java.lang.Class",{Hd:1,c:1,X:1});class Ac extends jc{}function Bc(){this.Ha=null;Cc=this;this.Ha=new Dc}Bc.prototype=new p;Bc.prototype.constructor=Bc;H(Bc,"scala.collection.Iterator$",{te:1,gb:1,c:1});var Cc;function Ec(){Cc||(Cc=new Bc);return Cc}function Fc(a){this.td=a}Fc.prototype=new uc;Fc.prototype.constructor=Fc;
Fc.prototype.G=function(a){(0,this.td)(a)};H(Fc,"scala.scalajs.runtime.AnonFunction1",{Ye:1,Ze:1,F:1});function Gc(){}Gc.prototype=new p;Gc.prototype.constructor=Gc;function Hc(){}Hc.prototype=Gc.prototype;var ma=H(0,"java.lang.Boolean",{Dd:1,c:1,ga:1,X:1},a=>"boolean"===typeof a),pa=H(0,"java.lang.Character",{Fd:1,c:1,ga:1,X:1},a=>a instanceof k);class N extends Ac{}H(N,"java.lang.RuntimeException",{R:1,H:1,I:1,c:1});function Cb(a){a.o="";return a}function zb(){this.o=null}zb.prototype=new p;
zb.prototype.constructor=zb;zb.prototype.C=function(){return this.o};zb.prototype.z=function(){return this.o.length};H(zb,"java.lang.StringBuilder",{Vd:1,hc:1,Wc:1,c:1});function Ic(){}Ic.prototype=new p;Ic.prototype.constructor=Ic;function Jc(){}g=Jc.prototype=Ic.prototype;g.B=function(){return this};g.C=function(){return"\x3citerator\x3e"};g.sa=function(a,b,c){return rb(this,a,b,c)};g.fc=function(a,b,c,d){return ub(this,a,b,c,d)};g.J=function(){return-1};function Kc(){this.Ia=null}
Kc.prototype=new p;Kc.prototype.constructor=Kc;function Lc(){}Lc.prototype=Kc.prototype;Kc.prototype.Ua=function(a){return this.Ia.Ta(a)};Kc.prototype.Ta=function(a){return this.Ua(a)};class Wc extends Ac{constructor(a,b){super();this.Mb=a;this.$c=b;K(this,null)}}H(Wc,"scala.util.CommandLineParser$ParseError",{ke:1,H:1,I:1,c:1});function Xc(){}Xc.prototype=new Hc;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;class Zc extends N{constructor(a){super();K(this,a)}}
H(Zc,"java.lang.ArithmeticException",{Cd:1,R:1,H:1,I:1,c:1});var fa=H(0,"java.lang.Byte",{Ed:1,Ga:1,c:1,ga:1,X:1},a=>"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0);function hb(a){var b=new Ka;K(b,a);return b}class Ka extends N{}H(Ka,"java.lang.IllegalArgumentException",{Yc:1,R:1,H:1,I:1,c:1});class $c extends N{constructor(a){super();K(this,a)}}H($c,"java.lang.IndexOutOfBoundsException",{Ld:1,R:1,H:1,I:1,c:1});function ad(){}ad.prototype=new Hc;ad.prototype.constructor=ad;
H(ad,"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Pd:1,Uc:1,Sc:1,Xc:1,Tc:1});class lb extends N{constructor(){super();K(this,null)}}H(lb,"java.lang.NegativeArraySizeException",{Rd:1,R:1,H:1,I:1,c:1});class Lb extends N{constructor(){super();K(this,null)}}H(Lb,"java.lang.NullPointerException",{Sd:1,R:1,H:1,I:1,c:1});var ha=H(0,"java.lang.Short",{Ud:1,Ga:1,c:1,ga:1,X:1},a=>"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0);class bd extends N{constructor(a){super();K(this,a)}}
H(bd,"java.lang.UnsupportedOperationException",{Yd:1,R:1,H:1,I:1,c:1});class cd extends N{constructor(a){super();K(this,a)}}H(cd,"java.util.NoSuchElementException",{ce:1,R:1,H:1,I:1,c:1});class U extends N{constructor(a){super();this.rc=null;this.Lb=!1;this.db=a;K(this,null)}Va(){if(!this.Lb&&!this.Lb){if(null===this.db)var a="null";else try{a=this.db+" (of class "+qa(this.db)+")"}catch(b){a="an instance of class "+qa(this.db)}this.rc=a;this.Lb=!0}return this.rc}}
H(U,"scala.MatchError",{fe:1,R:1,H:1,I:1,c:1});function Dc(){}Dc.prototype=new Jc;Dc.prototype.constructor=Dc;Dc.prototype.A=function(){return!1};Dc.prototype.J=function(){return 0};Dc.prototype.v=function(){throw new cd("next on empty iterator");};H(Dc,"scala.collection.Iterator$$anon$19",{ue:1,fb:1,hb:1,w:1,x:1});function dd(a,b){if(0>b)throw new $c(""+b);var c;a:for(c=b;;){if(0>=c||a===Sb()){c=a;break a}c=-1+c|0;a=a.Pa()}if(c===Sb())throw new $c(""+b);return c.Wa()}function ed(a){this.ib=a}
ed.prototype=new Jc;ed.prototype.constructor=ed;ed.prototype.A=function(){return this.ib!==Sb()};ed.prototype.v=function(){var a=this.ib.Wa();this.ib=this.ib.Pa();return a};H(ed,"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{xe:1,fb:1,hb:1,w:1,x:1});function Db(a,b){this.jb=a;this.gd=b;this.pa=a.length;this.t=0}Db.prototype=new Jc;Db.prototype.constructor=Db;Db.prototype.A=function(){return this.t<this.pa};
function Eb(a){if(a.t>=a.pa)a=Ec().Ha.v();else{for(var b=a.t;;){if(a.t<a.pa){var c=a.jb.charCodeAt(a.t);c=!(13===c||10===c)}else c=!1;if(c)a.t=1+a.t|0;else break}c=a.t;if(a.t<a.pa){var d=a.jb.charCodeAt(a.t);a.t=1+a.t|0;if(a.t<a.pa){var e=a.jb.charCodeAt(a.t);d=13===d&&10===e}else d=!1;d&&(a.t=1+a.t|0);a.gd||(c=a.t)}a=a.jb.substring(b,c)}return a}Db.prototype.v=function(){return Eb(this)};H(Db,"scala.collection.StringOps$$anon$1",{ze:1,fb:1,hb:1,w:1,x:1});function fd(){this.Ia=null;this.Ia=gd()}
fd.prototype=new Lc;fd.prototype.constructor=fd;function hd(a,b){return b&&b.$classData&&b.$classData.Q.qa?b:Kc.prototype.Ua.call(a,b)}fd.prototype.Ta=function(a){return hd(this,a)};fd.prototype.Ua=function(a){return hd(this,a)};H(fd,"scala.collection.immutable.IndexedSeq$",{Ce:1,dd:1,Pb:1,gb:1,c:1});var id;
function jd(){this.yc=null;kd=this;try{hc||(hc=new gc);var a=cb;bb||(bb=new ab);var b=a(bb,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250"),c=null===b?0:b.length;0===c&&bc(b);var d=b.charCodeAt(0),e=45===d;a=e?2147483648:2147483647;d=e||43===d?1:0;d>=b.length&&bc(b);for(e=0;d!==c;){ac||(ac=new $b);var f=ac,h=b.charCodeAt(d);if(256>h)var l=48<=h&&57>=h?-48+h|0:65<=h&&90>=h?-55+h|0:97<=h&&122>=h?-87+h|0:-1;else if(65313<=h&&65338>=h)l=-65303+h|0;else if(65345<=h&&65370>=h)l=
-65335+h|0;else{b:{Q();for(var q=Zb(f),w=0,A=q.a.length;;){if(w===A){var x=-1-w|0;break b}var C=(w+A|0)>>>1|0,v=q.a[C],u=h===v?0:h<v?-1:1;if(0>u)A=C;else{if(0===u){x=C;break b}w=1+C|0}}}w=0>x?-2-x|0:x;if(0>w)l=-1;else{var M=h-Zb(f).a[w]|0;l=9<M?-1:M}}var va=10>l?l:-1;e=10*e+va;(-1===va||e>a)&&bc(b);d=1+d|0}}catch(Mc){throw Mc;}this.yc=new ld(md(),0,0)}jd.prototype=new p;jd.prototype.constructor=jd;
function nd(a){if(a instanceof od)return a;var b=a.J();return 0===b?md():0<b&&32>=b?(a&&a.$classData&&a.$classData.Q.ba?(b=new r(b),a.sa(b,0,2147483647),a=b):(b=new r(b),a.B().sa(b,0,2147483647),a=b),new pd(a)):qd(rd(new sd,a))}jd.prototype.Ta=function(a){return nd(a)};H(jd,"scala.collection.immutable.Vector$",{Fe:1,fd:1,Pb:1,gb:1,c:1});var kd;function gd(){kd||(kd=new jd);return kd}
function td(a,b){var c=b.a.length;if(0<c){32===a.h&&ud(a);var d=32-a.h|0;d=d<c?d:c;c=c-d|0;b.f(0,a.l,a.h,d);a.h=a.h+d|0;0<c&&(ud(a),b.f(d,a.l,0,c),a.h=a.h+c|0)}}
var wd=function Z(a,b,c){if(0!==b.a.length){32===a.h&&ud(a);var e=b.a.length;switch(c){case 2:c=31&((1024-a.b|0)>>>5|0);c=c<e?c:e;e=e-c|0;b.f(0,a.d,31&(a.b>>>5|0),c);vd(a,c<<5);0<e&&(b.f(c,a.d,0,e),vd(a,e<<5));break;case 3:if(0!==(a.b%1024|0)){e=b.a.length;c=0;if(null!==b)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof D)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof G)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof E)for(;c<e;){var f=b.a[c];Z(a,new n(f.W,f.V),2);c=1+c|0}else if(b instanceof
F)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof y)for(;c<e;)Z(a,new k(b.a[c]),2),c=1+c|0;else if(b instanceof z)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof B)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else if(b instanceof t)for(;c<e;)Z(a,b.a[c],2),c=1+c|0;else throw new U(b);break}c=31&((32768-a.b|0)>>>10|0);c=c<e?c:e;e=e-c|0;b.f(0,a.g,31&(a.b>>>10|0),c);vd(a,c<<10);0<e&&(b.f(c,a.g,0,e),vd(a,e<<10));break;case 4:if(0!==(a.b%32768|0)){e=b.a.length;c=0;if(null!==b)for(;c<e;)Z(a,b.a[c],3),c=1+c|
0;else if(b instanceof D)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else if(b instanceof G)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else if(b instanceof E)for(;c<e;)f=b.a[c],Z(a,new n(f.W,f.V),3),c=1+c|0;else if(b instanceof F)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else if(b instanceof y)for(;c<e;)Z(a,new k(b.a[c]),3),c=1+c|0;else if(b instanceof z)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else if(b instanceof B)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else if(b instanceof t)for(;c<e;)Z(a,b.a[c],3),c=1+c|0;else throw new U(b);break}c=31&((1048576-
a.b|0)>>>15|0);c=c<e?c:e;e=e-c|0;b.f(0,a.k,31&(a.b>>>15|0),c);vd(a,c<<15);0<e&&(b.f(c,a.k,0,e),vd(a,e<<15));break;case 5:if(0!==(a.b%1048576|0)){e=b.a.length;c=0;if(null!==b)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof D)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof G)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof E)for(;c<e;)f=b.a[c],Z(a,new n(f.W,f.V),4),c=1+c|0;else if(b instanceof F)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof y)for(;c<e;)Z(a,new k(b.a[c]),4),c=1+
c|0;else if(b instanceof z)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof B)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else if(b instanceof t)for(;c<e;)Z(a,b.a[c],4),c=1+c|0;else throw new U(b);break}c=31&((33554432-a.b|0)>>>20|0);c=c<e?c:e;e=e-c|0;b.f(0,a.n,31&(a.b>>>20|0),c);vd(a,c<<20);0<e&&(b.f(c,a.n,0,e),vd(a,e<<20));break;case 6:if(0!==(a.b%33554432|0)){e=b.a.length;c=0;if(null!==b)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof D)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof G)for(;c<
e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof E)for(;c<e;)f=b.a[c],Z(a,new n(f.W,f.V),5),c=1+c|0;else if(b instanceof F)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof y)for(;c<e;)Z(a,new k(b.a[c]),5),c=1+c|0;else if(b instanceof z)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof B)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else if(b instanceof t)for(;c<e;)Z(a,b.a[c],5),c=1+c|0;else throw new U(b);break}c=a.b>>>25|0;if(64<(c+e|0))throw hb("exceeding 2^31 elements");b.f(0,a.r,c,e);vd(a,e<<25);break;
default:throw new U(c);}}};function xd(a,b){for(var c=b.da(),d=0;d<c;){var e=b.ea(d),f=c/2|0,h=d-f|0;f=(1+f|0)-(0>h?-h|0:h)|0;1===f?td(a,e):32===a.h||0===a.h?wd(a,e,f):Jb(T(),-2+f|0,e,new Fc(l=>{td(a,l)}));d=1+d|0}return a}function ud(a){var b=32+a.b|0,c=b^a.b;a.b=b;a.h=0;yd(a,b,c)}function vd(a,b){if(0<b){b=a.b+b|0;var c=b^a.b;a.b=b;a.h=0;yd(a,b,c)}}
function yd(a,b,c){if(0>=c)throw hb("advance1("+b+", "+c+"): a1\x3d"+a.l+", a2\x3d"+a.d+", a3\x3d"+a.g+", a4\x3d"+a.k+", a5\x3d"+a.n+", a6\x3d"+a.r+", depth\x3d"+a.i);1024>c?(1>=a.i&&(a.d=new (J(J(I)).m)(32),a.d.a[0]=a.l,a.i=2),a.l=new r(32),a.d.a[31&(b>>>5|0)]=a.l):32768>c?(2>=a.i&&(a.g=new (J(J(J(I))).m)(32),a.g.a[0]=a.d,a.i=3),a.l=new r(32),a.d=new (J(J(I)).m)(32),a.d.a[31&(b>>>5|0)]=a.l,a.g.a[31&(b>>>10|0)]=a.d):1048576>c?(3>=a.i&&(a.k=new (J(J(J(J(I)))).m)(32),a.k.a[0]=a.g,a.i=4),a.l=new r(32),
a.d=new (J(J(I)).m)(32),a.g=new (J(J(J(I))).m)(32),a.d.a[31&(b>>>5|0)]=a.l,a.g.a[31&(b>>>10|0)]=a.d,a.k.a[31&(b>>>15|0)]=a.g):33554432>c?(4>=a.i&&(a.n=new (J(J(J(J(J(I))))).m)(32),a.n.a[0]=a.k,a.i=5),a.l=new r(32),a.d=new (J(J(I)).m)(32),a.g=new (J(J(J(I))).m)(32),a.k=new (J(J(J(J(I)))).m)(32),a.d.a[31&(b>>>5|0)]=a.l,a.g.a[31&(b>>>10|0)]=a.d,a.k.a[31&(b>>>15|0)]=a.g,a.n.a[31&(b>>>20|0)]=a.k):(5>=a.i&&(a.r=new (J(J(J(J(J(J(I)))))).m)(64),a.r.a[0]=a.n,a.i=6),a.l=new r(32),a.d=new (J(J(I)).m)(32),a.g=
new (J(J(J(I))).m)(32),a.k=new (J(J(J(J(I)))).m)(32),a.n=new (J(J(J(J(J(I))))).m)(32),a.d.a[31&(b>>>5|0)]=a.l,a.g.a[31&(b>>>10|0)]=a.d,a.k.a[31&(b>>>15|0)]=a.g,a.n.a[31&(b>>>20|0)]=a.k,a.r.a[b>>>25|0]=a.n)}function sd(){this.l=this.d=this.g=this.k=this.n=this.r=null;this.e=this.b=this.h=0;this.Cb=!1;this.i=0;this.l=new r(32);this.e=this.b=this.h=0;this.Cb=!1;this.i=1}sd.prototype=new p;sd.prototype.constructor=sd;
function rd(a,b){if(b instanceof od)if(0!==a.h||0!==a.b||a.Cb)a=xd(a,b);else{var c=b.da();switch(c){case 0:break;case 1:a.i=1;c=b.j.a.length;a.h=31&c;a.b=c-a.h|0;b=b.j;a.l=32===b.a.length?b:P(Q(),b,0,32);break;case 3:c=b.nb;var d=b.q;a.l=32===d.a.length?d:P(Q(),d,0,32);a.i=2;a.e=32-b.zc|0;d=b.p+a.e|0;a.h=31&d;a.b=d-a.h|0;a.d=new (J(J(I)).m)(32);a.d.a[0]=b.j;c.f(0,a.d,1,c.a.length);a.d.a[1+c.a.length|0]=a.l;break;case 5:c=b.ob;d=b.pb;var e=b.q;a.l=32===e.a.length?e:P(Q(),e,0,32);a.i=3;a.e=1024-b.Bc|
0;e=b.p+a.e|0;a.h=31&e;a.b=e-a.h|0;a.g=new (J(J(J(I))).m)(32);a.g.a[0]=Ib(T(),b.j,b.Tb);c.f(0,a.g,1,c.a.length);a.d=O(Q(),d,32);a.g.a[1+c.a.length|0]=a.d;a.d.a[d.a.length]=a.l;break;case 7:c=b.qb;d=b.sb;e=b.rb;var f=b.q;a.l=32===f.a.length?f:P(Q(),f,0,32);a.i=4;a.e=32768-b.Ec|0;f=b.p+a.e|0;a.h=31&f;a.b=f-a.h|0;a.k=new (J(J(J(J(I)))).m)(32);a.k.a[0]=Ib(T(),Ib(T(),b.j,b.Ub),b.Vb);c.f(0,a.k,1,c.a.length);a.g=O(Q(),d,32);a.d=O(Q(),e,32);a.k.a[1+c.a.length|0]=a.g;a.g.a[d.a.length]=a.d;a.d.a[e.a.length]=
a.l;break;case 9:c=b.tb;d=b.wb;e=b.vb;f=b.ub;var h=b.q;a.l=32===h.a.length?h:P(Q(),h,0,32);a.i=5;a.e=1048576-b.Ic|0;h=b.p+a.e|0;a.h=31&h;a.b=h-a.h|0;a.n=new (J(J(J(J(J(I))))).m)(32);a.n.a[0]=Ib(T(),Ib(T(),Ib(T(),b.j,b.Wb),b.Xb),b.Yb);c.f(0,a.n,1,c.a.length);a.k=O(Q(),d,32);a.g=O(Q(),e,32);a.d=O(Q(),f,32);a.n.a[1+c.a.length|0]=a.k;a.k.a[d.a.length]=a.g;a.g.a[e.a.length]=a.d;a.d.a[f.a.length]=a.l;break;case 11:c=b.xb;d=b.Bb;e=b.Ab;f=b.zb;h=b.yb;var l=b.q;a.l=32===l.a.length?l:P(Q(),l,0,32);a.i=6;a.e=
33554432-b.Nc|0;l=b.p+a.e|0;a.h=31&l;a.b=l-a.h|0;a.r=new (J(J(J(J(J(J(I)))))).m)(64);a.r.a[0]=Ib(T(),Ib(T(),Ib(T(),Ib(T(),b.j,b.Zb),b.$b),b.ac),b.bc);c.f(0,a.r,1,c.a.length);a.n=O(Q(),d,32);a.k=O(Q(),e,32);a.g=O(Q(),f,32);a.d=O(Q(),h,32);a.r.a[1+c.a.length|0]=a.n;a.n.a[d.a.length]=a.k;a.k.a[e.a.length]=a.g;a.g.a[f.a.length]=a.d;a.d.a[h.a.length]=a.l;break;default:throw new U(c);}0===a.h&&0<a.b&&(a.h=32,a.b=-32+a.b|0)}else a=qc(a,b);return a}
function qd(a){if(a.Cb){var b=null,c=null;if(6<=a.i){b=a.r;var d=a.e>>>25|0;0<d&&b.f(d,b,0,64-d|0);var e=a.e%33554432|0;a.b=a.b-(a.e-e|0)|0;a.e=e;0===(a.b>>>25|0)&&(a.i=5);c=b;b=b.a[0]}if(5<=a.i){null===b&&(b=a.n);var f=31&(a.e>>>20|0);if(5===a.i){0<f&&b.f(f,b,0,32-f|0);a.n=b;var h=a.e%1048576|0;a.b=a.b-(a.e-h|0)|0;a.e=h;0===(a.b>>>20|0)&&(a.i=4)}else 0<f&&(b=P(Q(),b,f,32)),c.a[0]=b;c=b;b=b.a[0]}if(4<=a.i){null===b&&(b=a.k);var l=31&(a.e>>>15|0);if(4===a.i){0<l&&b.f(l,b,0,32-l|0);a.k=b;var q=a.e%
32768|0;a.b=a.b-(a.e-q|0)|0;a.e=q;0===(a.b>>>15|0)&&(a.i=3)}else 0<l&&(b=P(Q(),b,l,32)),c.a[0]=b;c=b;b=b.a[0]}if(3<=a.i){null===b&&(b=a.g);var w=31&(a.e>>>10|0);if(3===a.i){0<w&&b.f(w,b,0,32-w|0);a.g=b;var A=a.e%1024|0;a.b=a.b-(a.e-A|0)|0;a.e=A;0===(a.b>>>10|0)&&(a.i=2)}else 0<w&&(b=P(Q(),b,w,32)),c.a[0]=b;c=b;b=b.a[0]}if(2<=a.i){null===b&&(b=a.d);var x=31&(a.e>>>5|0);if(2===a.i){0<x&&b.f(x,b,0,32-x|0);a.d=b;var C=a.e%32|0;a.b=a.b-(a.e-C|0)|0;a.e=C;0===(a.b>>>5|0)&&(a.i=1)}else 0<x&&(b=P(Q(),b,x,
32)),c.a[0]=b;c=b;b=b.a[0]}if(1<=a.i){null===b&&(b=a.l);var v=31&a.e;1===a.i?(0<v&&b.f(v,b,0,32-v|0),a.l=b,a.h=a.h-a.e|0,a.e=0):(0<v&&(b=P(Q(),b,v,32)),c.a[0]=b)}a.Cb=!1}var u=a.h+a.b|0,M=u-a.e|0;if(0===M)return gd(),md();if(0>u)throw new $c("Vector cannot have negative size "+u);if(32>=u){var va=a.l;return new pd(va.a.length===M?va:O(Q(),va,M))}if(1024>=u){var Mc=31&(-1+u|0),$d=(-1+u|0)>>>5|0,Ff=P(Q(),a.d,1,$d),Gf=a.d.a[0],Nc=a.d.a[$d],ae=1+Mc|0,Hf=Nc.a.length===ae?Nc:O(Q(),Nc,ae);return new zd(Gf,
32-a.e|0,Ff,Hf,M)}if(32768>=u){var If=31&(-1+u|0),be=31&((-1+u|0)>>>5|0),Oc=(-1+u|0)>>>10|0,Jf=P(Q(),a.g,1,Oc),ce=a.g.a[0],de=P(Q(),ce,1,ce.a.length),ee=a.g.a[0].a[0],Kf=O(Q(),a.g.a[Oc],be),Pc=a.g.a[Oc].a[be],fe=1+If|0,Lf=Pc.a.length===fe?Pc:O(Q(),Pc,fe),ge=ee.a.length;return new Ad(ee,ge,de,ge+(de.a.length<<5)|0,Jf,Kf,Lf,M)}if(1048576>=u){var Mf=31&(-1+u|0),he=31&((-1+u|0)>>>5|0),Qc=31&((-1+u|0)>>>10|0),cc=(-1+u|0)>>>15|0,Nf=P(Q(),a.k,1,cc),ie=a.k.a[0],je=P(Q(),ie,1,ie.a.length),ke=a.k.a[0].a[0],
le=P(Q(),ke,1,ke.a.length),me=a.k.a[0].a[0].a[0],Of=O(Q(),a.k.a[cc],Qc),Pf=O(Q(),a.k.a[cc].a[Qc],he),Rc=a.k.a[cc].a[Qc].a[he],ne=1+Mf|0,Qf=Rc.a.length===ne?Rc:O(Q(),Rc,ne),oe=me.a.length,pe=oe+(le.a.length<<5)|0;return new Bd(me,oe,le,pe,je,pe+(je.a.length<<10)|0,Nf,Of,Pf,Qf,M)}if(33554432>=u){var Rf=31&(-1+u|0),qe=31&((-1+u|0)>>>5|0),Sc=31&((-1+u|0)>>>10|0),dc=31&((-1+u|0)>>>15|0),Ab=(-1+u|0)>>>20|0,Sf=P(Q(),a.n,1,Ab),re=a.n.a[0],se=P(Q(),re,1,re.a.length),te=a.n.a[0].a[0],ue=P(Q(),te,1,te.a.length),
ve=a.n.a[0].a[0].a[0],we=P(Q(),ve,1,ve.a.length),xe=a.n.a[0].a[0].a[0].a[0],Tf=O(Q(),a.n.a[Ab],dc),Uf=O(Q(),a.n.a[Ab].a[dc],Sc),Vf=O(Q(),a.n.a[Ab].a[dc].a[Sc],qe),Tc=a.n.a[Ab].a[dc].a[Sc].a[qe],ye=1+Rf|0,Wf=Tc.a.length===ye?Tc:O(Q(),Tc,ye),ze=xe.a.length,Ae=ze+(we.a.length<<5)|0,Be=Ae+(ue.a.length<<10)|0;return new Cd(xe,ze,we,Ae,ue,Be,se,Be+(se.a.length<<15)|0,Sf,Tf,Uf,Vf,Wf,M)}var Xf=31&(-1+u|0),Ce=31&((-1+u|0)>>>5|0),Uc=31&((-1+u|0)>>>10|0),ec=31&((-1+u|0)>>>15|0),Bb=31&((-1+u|0)>>>20|0),Pa=(-1+
u|0)>>>25|0,Yf=P(Q(),a.r,1,Pa),De=a.r.a[0],Ee=P(Q(),De,1,De.a.length),Fe=a.r.a[0].a[0],Ge=P(Q(),Fe,1,Fe.a.length),He=a.r.a[0].a[0].a[0],Ie=P(Q(),He,1,He.a.length),Je=a.r.a[0].a[0].a[0].a[0],Ke=P(Q(),Je,1,Je.a.length),Le=a.r.a[0].a[0].a[0].a[0].a[0],Zf=O(Q(),a.r.a[Pa],Bb),$f=O(Q(),a.r.a[Pa].a[Bb],ec),ag=O(Q(),a.r.a[Pa].a[Bb].a[ec],Uc),bg=O(Q(),a.r.a[Pa].a[Bb].a[ec].a[Uc],Ce),Vc=a.r.a[Pa].a[Bb].a[ec].a[Uc].a[Ce],Me=1+Xf|0,cg=Vc.a.length===Me?Vc:O(Q(),Vc,Me),Ne=Le.a.length,Oe=Ne+(Ke.a.length<<5)|0,Pe=
Oe+(Ie.a.length<<10)|0,Qe=Pe+(Ge.a.length<<15)|0;return new Dd(Le,Ne,Ke,Oe,Ie,Pe,Ge,Qe,Ee,Qe+(Ee.a.length<<20)|0,Yf,Zf,$f,ag,bg,cg,M)}sd.prototype.C=function(){return"VectorBuilder(len1\x3d"+this.h+", lenRest\x3d"+this.b+", offset\x3d"+this.e+", depth\x3d"+this.i+")"};sd.prototype.Kb=function(){return qd(this)};sd.prototype.Eb=function(a){rd(this,a)};sd.prototype.Fb=function(a){32===this.h&&ud(this);this.l.a[this.h]=a;this.h=1+this.h|0};
H(sd,"scala.collection.immutable.VectorBuilder",{Ne:1,qd:1,Oc:1,Qc:1,Pc:1});function sc(){this.Ia=null;Ed||(Ed=new Fd);this.Ia=Ed}sc.prototype=new Lc;sc.prototype.constructor=sc;H(sc,"scala.collection.mutable.Buffer$",{Re:1,dd:1,Pb:1,gb:1,c:1});var rc;function Fd(){}Fd.prototype=new p;Fd.prototype.constructor=Fd;Fd.prototype.Ta=function(a){var b=new Gd;b.ya=[];return qc(b,a).Kb()};H(Fd,"scala.scalajs.js.WrappedArray$",{Xe:1,fd:1,Pb:1,gb:1,c:1});var Ed;function ta(a){return Va(Wa(),a)}
var la=H(0,"java.lang.Double",{Id:1,Ga:1,c:1,ga:1,X:1,bb:1},a=>"number"===typeof a),ka=H(0,"java.lang.Float",{Jd:1,Ga:1,c:1,ga:1,X:1,bb:1},a=>ja(a)),ia=H(0,"java.lang.Integer",{Md:1,Ga:1,c:1,ga:1,X:1,bb:1},a=>ea(a)),oa=H(0,"java.lang.Long",{Qd:1,Ga:1,c:1,ga:1,X:1,bb:1},a=>a instanceof n);class fc extends Ka{constructor(a){super();K(this,a)}}H(fc,"java.lang.NumberFormatException",{Td:1,Yc:1,R:1,H:1,I:1,c:1});
function sa(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}function Hd(a){for(var b=a.length,c=0;c!==b&&32>=a.charCodeAt(c);)c=1+c|0;if(c===b)return"";for(var d=b;32>=a.charCodeAt(-1+d|0);)d=-1+d|0;return 0===c&&d===b?a:a.substring(c,d)}var da=H(0,"java.lang.String",{Ad:1,c:1,ga:1,hc:1,X:1,bb:1},a=>"string"===typeof a);function Id(){}Id.prototype=new p;Id.prototype.constructor=Id;function Jd(){}Jd.prototype=Id.prototype;
Id.prototype.Da=function(){return this.Oa()};Id.prototype.sa=function(a,b,c){return rb(this,a,b,c)};Id.prototype.fc=function(a,b,c,d){return ub(this,a,b,c,d)};Id.prototype.J=function(){return-1};function Kd(a){this.ta=0;this.ad=a;this.Ob=0;this.ta=a.z()}Kd.prototype=new Jc;Kd.prototype.constructor=Kd;Kd.prototype.J=function(){return this.ta};Kd.prototype.A=function(){return 0<this.ta};Kd.prototype.v=function(){if(0<this.ta){var a=this.ad.s(this.Ob);this.Ob=1+this.Ob|0;this.ta=-1+this.ta|0;return a}return Ec().Ha.v()};
H(Kd,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{se:1,fb:1,hb:1,w:1,x:1,c:1});
function Ld(a){var b=(a.u-a.ja|0)+a.mb|0;if(b===a.Na){a.ja<=a.u&&Ec().Ha.v();a.ra=1+a.ra|0;for(var c=a.xc.ea(a.ra);0===c.a.length;)a.ra=1+a.ra|0,c=a.xc.ea(a.ra);a.Sb=a.Na;var d=a.kd/2|0,e=a.ra-d|0;a.va=(1+d|0)-(0>e?-e|0:e)|0;d=a.va;switch(d){case 1:a.ca=c;break;case 2:a.Ka=c;break;case 3:a.La=c;break;case 4:a.Ma=c;break;case 5:a.lb=c;break;case 6:a.wc=c;break;default:throw new U(d);}a.Na=a.Sb+Math.imul(c.a.length,1<<Math.imul(5,-1+a.va|0))|0;a.Na>a.mb&&(a.Na=a.mb);1<a.va&&(a.Rb=-1+(1<<Math.imul(5,
a.va))|0)}1<a.va&&(b=b-a.Sb|0,c=a.Rb^b,1024>c?a.ca=a.Ka.a[31&(b>>>5|0)]:(32768>c?a.Ka=a.La.a[31&(b>>>10|0)]:(1048576>c?a.La=a.Ma.a[31&(b>>>15|0)]:(33554432>c?a.Ma=a.lb.a[31&(b>>>20|0)]:(a.lb=a.wc.a[b>>>25|0],a.Ma=a.lb.a[0]),a.La=a.Ma.a[0]),a.Ka=a.La.a[0]),a.ca=a.Ka.a[0]),a.Rb=b);a.ja=a.ja-a.u|0;b=a.ca.a.length;c=a.ja;a.kb=b<c?b:c;a.u=0}
function ld(a,b,c){this.wc=this.lb=this.Ma=this.La=this.Ka=null;this.xc=a;this.mb=b;this.kd=c;this.ca=a.j;this.kb=this.ca.a.length;this.Rb=this.u=0;this.ja=this.mb;this.ra=0;this.va=1;this.Sb=0;this.Na=this.kb}ld.prototype=new Jc;ld.prototype.constructor=ld;ld.prototype.J=function(){return this.ja-this.u|0};ld.prototype.A=function(){return this.ja>this.u};ld.prototype.v=function(){this.u===this.kb&&Ld(this);var a=this.ca.a[this.u];this.u=1+this.u|0;return a};
ld.prototype.sa=function(a,b,c){var d=gb(jb(),a),e=this.ja-this.u|0;c=c<e?c:e;d=d-b|0;d=c<d?c:d;d=0<d?d:0;c=0;for(e=a instanceof r;c<d;){this.u===this.kb&&Ld(this);var f=d-c|0,h=this.ca.a.length-this.u|0;f=f<h?f:h;if(e)this.ca.f(this.u,a,b+c|0,f);else{lc||(lc=new kc);var l=this.ca;h=this.u;var q=a,w=b+c|0,A=f,x=ca(l),C;if(C=x.D.Gb)C=ca(q).D,x=x.D,C=C===x||C.oa(x);if(C)l.f(h,q,w,A);else for(x=h,h=h+A|0;x<h;){tb();A=q;C=w;tb();var v=l;if(v instanceof r||v instanceof D||v instanceof G||v instanceof E||
v instanceof F)v=v.a[x];else if(v instanceof y)v=new k(v.a[x]);else if(v instanceof z||v instanceof B||v instanceof t)v=v.a[x];else{if(null===v)throw new Lb;throw new U(v);}sb(0,A,C,v);x=1+x|0;w=1+w|0}}this.u=this.u+f|0;c=c+f|0}return d};H(ld,"scala.collection.immutable.NewVectorIterator",{De:1,fb:1,hb:1,w:1,x:1,Za:1});function Md(){}Md.prototype=new Yc;Md.prototype.constructor=Md;function Nd(){}Nd.prototype=Md.prototype;function Od(a){var b=pc().pc.Nb;Pd(b,null===a?"null":a);Pd(b,"\n")}
class ic extends N{constructor(a){super();this.dc=a;K(this,null)}Va(){return wa(this.dc)}cb(){return"JavaScriptException"}Ib(){return 1}Jb(a){if(0===a)a=this.dc;else throw W(),new $c(""+a);return a}fa(){zc();var a=this.Ib();if(0===a)a=sa(this.cb());else{var b=X(-889275714,sa(this.cb()));for(var c=0;c<a;)b=X(b,V(W(),this.Jb(c))),c=1+c|0;a=Y(b^a)}return a}}H(ic,"scala.scalajs.js.JavaScriptException",{Ve:1,R:1,H:1,I:1,c:1,sc:1,K:1});function Za(a){this.Zc=a;this.ab=""}Za.prototype=new Nd;
Za.prototype.constructor=Za;function Pd(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.ab=""+a.ab+b,b="";else{var d=""+a.ab+b.substring(0,c);"undefined"!==typeof console&&(a.Zc&&console.error?console.error(d):console.log(d));a.ab="";b=b.substring(1+c|0)}}}H(Za,"java.lang.JSConsoleBasedPrintStream",{Od:1,xd:1,wd:1,Uc:1,Sc:1,Xc:1,Tc:1,Wc:1});function Qd(){}Qd.prototype=new Jd;Qd.prototype.constructor=Qd;function Rd(){}Rd.prototype=Qd.prototype;Qd.prototype.C=function(){return this.Da()+"(\x3cnot computed\x3e)"};
function Sd(){}Sd.prototype=new Jd;Sd.prototype.constructor=Sd;function Td(){}Td.prototype=Sd.prototype;
Sd.prototype.fa=function(){var a=zc();if(this&&this.$classData&&this.$classData.Q.Y)a:{a=a.eb;var b=this.z();switch(b){case 0:a=Y(a^0);break a;case 1:a=Y(X(a,V(W(),this.s(0)))^1);break a;default:var c=V(W(),this.s(0)),d=a=X(a,c),e=V(W(),this.s(1));c=e-c|0;for(var f=2;f<b;){a=X(a,e);var h=V(W(),this.s(f));if(c!==(h-e|0)){a=X(a,h);for(f=1+f|0;f<b;)a=X(a,V(W(),this.s(f))),f=1+f|0;a=Y(a^b);break a}e=h;f=1+f|0}a=Y(X(X(d,c),e))}}else if(this instanceof Ud){a=a.eb;e=0;c=a;b=d=h=f=0;for(var l=this;l!==Sb();){var q=
l.Wa();l=l.Pa();q=V(W(),q);c=X(c,q);switch(f){case 0:b=q;f=1;break;case 1:h=q-d|0;f=2;break;case 2:h!==(q-d|0)&&(f=3)}d=q;e=1+e|0}2===f?(e=h,a=Y(X(X(X(a,b),e),d))):a=Y(c^e)}else a:if(b=a.eb,a=this.B(),a.A())if(d=a.v(),a.A()){e=a.v();c=V(W(),d);d=b=X(b,c);e=V(W(),e);c=e-c|0;for(f=2;a.A();){b=X(b,e);h=V(W(),a.v());if(c!==(h-e|0)){b=X(b,h);for(f=1+f|0;a.A();)b=X(b,V(W(),a.v())),f=1+f|0;a=Y(b^f);break a}e=h;f=1+f|0}a=Y(X(X(d,c),e))}else a=Y(X(b,V(W(),d))^1);else a=Y(b^0);return a};
Sd.prototype.C=function(){var a=this.Da()+"(";return 0===this.J()?""+a+")":this.fc(Vd(),a,", ",")").E.o};function Wd(){}Wd.prototype=new Rd;Wd.prototype.constructor=Wd;function Xd(){}Xd.prototype=Wd.prototype;function Yd(){this.Qb=null}Yd.prototype=new Xd;Yd.prototype.constructor=Yd;function Zd(){}Zd.prototype=Yd.prototype;Yd.prototype.s=function(a){return this.Qb.s(a)};Yd.prototype.z=function(){return this.Qb.z()};function Re(a){this.Qb=a}Re.prototype=new Zd;Re.prototype.constructor=Re;
Re.prototype.B=function(){return new Kd(this)};Re.prototype.Oa=function(){return"IndexedSeqView"};Re.prototype.J=function(){return this.z()};H(Re,"scala.collection.IndexedSeqView$Id",{re:1,we:1,oe:1,pe:1,L:1,M:1,w:1,O:1,x:1,N:1,Ae:1,c:1,ve:1,P:1,qe:1,Z:1});function Se(){}Se.prototype=new Td;Se.prototype.constructor=Se;function Te(){}Te.prototype=Se.prototype;function Ue(){}Ue.prototype=new Td;Ue.prototype.constructor=Ue;function Ve(){}Ve.prototype=Ue.prototype;function We(){}We.prototype=new Ve;
We.prototype.constructor=We;function Xe(){}Xe.prototype=We.prototype;We.prototype.Eb=function(a){qc(this,a)};function od(){this.j=null}od.prototype=new Te;od.prototype.constructor=od;function Ye(){}g=Ye.prototype=od.prototype;g.Oa=function(){return"IndexedSeq"};g.J=function(){return this.z()};g.z=function(){return this instanceof Ze?this.p:this.j.a.length};g.B=function(){return md()===this?gd().yc:new ld(this,this.z(),this.da())};g.Da=function(){return"Vector"};
g.sa=function(a,b,c){return this.B().sa(a,b,c)};g.y=function(a){return new $c(a+" is out of bounds (min 0, max "+(-1+this.z()|0)+")")};function Ud(){}Ud.prototype=new Te;Ud.prototype.constructor=Ud;function $e(){}g=$e.prototype=Ud.prototype;g.B=function(){return new ed(this)};g.Oa=function(){return"LinearSeq"};g.s=function(a){return dd(this,a)};g.z=function(){for(var a=this,b=0;a!==Sb();)b=1+b|0,a=a.Pa();return b};g.Da=function(){return"List"};g.G=function(a){dd(this,a|0)};
function af(){this.j=null}af.prototype=new Ye;af.prototype.constructor=af;function bf(){}bf.prototype=af.prototype;function cf(a,b,c,d){a.q=c;a.p=d;a.j=b}function Ze(){this.q=this.j=null;this.p=0}Ze.prototype=new bf;Ze.prototype.constructor=Ze;function df(){}df.prototype=Ze.prototype;function pd(a){this.j=a}pd.prototype=new bf;pd.prototype.constructor=pd;pd.prototype.s=function(a){if(0<=a&&a<this.j.a.length)return this.j.a[a];throw this.y(a);};pd.prototype.da=function(){return 1};
pd.prototype.ea=function(){return this.j};pd.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.j.a.length))throw this.y(a);};H(pd,"scala.collection.immutable.Vector1",{He:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});function Rb(a,b){this.uc=a;this.vc=b}Rb.prototype=new $e;Rb.prototype.constructor=Rb;g=Rb.prototype;g.Wa=function(){return this.uc};g.cb=function(){return"::"};g.Ib=function(){return 2};
g.Jb=function(a){switch(a){case 0:return this.uc;case 1:return this.vc;default:throw W(),new $c(""+a);}};g.Pa=function(){return this.vc};H(Rb,"scala.collection.immutable.$colon$colon",{Be:1,jd:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,hd:1,bd:1,cd:1,id:1,ed:1,aa:1,$:1,ma:1,ha:1,c:1,sc:1});function ef(){}ef.prototype=new $e;ef.prototype.constructor=ef;g=ef.prototype;g.J=function(){return 0};g.B=function(){return Ec().Ha};g.cb=function(){return"Nil"};g.Ib=function(){return 0};
g.Jb=function(a){W();throw new $c(""+a);};g.Pa=function(){throw new bd("tail of empty list");};g.Wa=function(){throw new cd("head of empty list");};H(ef,"scala.collection.immutable.Nil$",{Ee:1,jd:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,hd:1,bd:1,cd:1,id:1,ed:1,aa:1,$:1,ma:1,ha:1,c:1,sc:1});var ff;function Sb(){ff||(ff=new ef);return ff}function gf(){this.q=this.j=null;this.p=0;cf(this,T().cc,T().cc,0)}gf.prototype=new df;gf.prototype.constructor=gf;g=gf.prototype;
g.da=function(){return 0};g.ea=function(){return null};g.y=function(a){return new $c(a+" is out of bounds (empty vector)")};g.G=function(a){throw this.y(a|0);};g.s=function(a){throw this.y(a);};H(gf,"scala.collection.immutable.Vector0$",{Ge:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});var hf;function md(){hf||(hf=new gf);return hf}
function zd(a,b,c,d,e){this.q=this.j=null;this.p=0;this.zc=b;this.nb=c;cf(this,a,d,e)}zd.prototype=new df;zd.prototype.constructor=zd;zd.prototype.s=function(a){if(0<=a&&a<this.p){var b=a-this.zc|0;return 0<=b?(a=b>>>5|0,a<this.nb.a.length?this.nb.a[a].a[31&b]:this.q.a[31&b]):this.j.a[a]}throw this.y(a);};zd.prototype.da=function(){return 3};zd.prototype.ea=function(a){switch(a){case 0:return this.j;case 1:return this.nb;case 2:return this.q;default:throw new U(a);}};
zd.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.p))throw this.y(a);};H(zd,"scala.collection.immutable.Vector2",{Ie:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});function Ad(a,b,c,d,e,f,h,l){this.q=this.j=null;this.p=0;this.Ac=b;this.Tb=c;this.Bc=d;this.ob=e;this.pb=f;cf(this,a,h,l)}Ad.prototype=new df;Ad.prototype.constructor=Ad;
Ad.prototype.s=function(a){if(0<=a&&a<this.p){var b=a-this.Bc|0;if(0<=b){a=b>>>10|0;var c=31&(b>>>5|0);b&=31;return a<this.ob.a.length?this.ob.a[a].a[c].a[b]:c<this.pb.a.length?this.pb.a[c].a[b]:this.q.a[b]}return a>=this.Ac?(b=a-this.Ac|0,this.Tb.a[b>>>5|0].a[31&b]):this.j.a[a]}throw this.y(a);};Ad.prototype.da=function(){return 5};
Ad.prototype.ea=function(a){switch(a){case 0:return this.j;case 1:return this.Tb;case 2:return this.ob;case 3:return this.pb;case 4:return this.q;default:throw new U(a);}};Ad.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.p))throw this.y(a);};H(Ad,"scala.collection.immutable.Vector3",{Je:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});
function Bd(a,b,c,d,e,f,h,l,q,w,A){this.q=this.j=null;this.p=0;this.Cc=b;this.Ub=c;this.Dc=d;this.Vb=e;this.Ec=f;this.qb=h;this.sb=l;this.rb=q;cf(this,a,w,A)}Bd.prototype=new df;Bd.prototype.constructor=Bd;
Bd.prototype.s=function(a){if(0<=a&&a<this.p){var b=a-this.Ec|0;if(0<=b){a=b>>>15|0;var c=31&(b>>>10|0),d=31&(b>>>5|0);b&=31;return a<this.qb.a.length?this.qb.a[a].a[c].a[d].a[b]:c<this.sb.a.length?this.sb.a[c].a[d].a[b]:d<this.rb.a.length?this.rb.a[d].a[b]:this.q.a[b]}return a>=this.Dc?(b=a-this.Dc|0,this.Vb.a[b>>>10|0].a[31&(b>>>5|0)].a[31&b]):a>=this.Cc?(b=a-this.Cc|0,this.Ub.a[b>>>5|0].a[31&b]):this.j.a[a]}throw this.y(a);};Bd.prototype.da=function(){return 7};
Bd.prototype.ea=function(a){switch(a){case 0:return this.j;case 1:return this.Ub;case 2:return this.Vb;case 3:return this.qb;case 4:return this.sb;case 5:return this.rb;case 6:return this.q;default:throw new U(a);}};Bd.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.p))throw this.y(a);};H(Bd,"scala.collection.immutable.Vector4",{Ke:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});
function Cd(a,b,c,d,e,f,h,l,q,w,A,x,C,v){this.q=this.j=null;this.p=0;this.Fc=b;this.Wb=c;this.Gc=d;this.Xb=e;this.Hc=f;this.Yb=h;this.Ic=l;this.tb=q;this.wb=w;this.vb=A;this.ub=x;cf(this,a,C,v)}Cd.prototype=new df;Cd.prototype.constructor=Cd;
Cd.prototype.s=function(a){if(0<=a&&a<this.p){var b=a-this.Ic|0;if(0<=b){a=b>>>20|0;var c=31&(b>>>15|0),d=31&(b>>>10|0),e=31&(b>>>5|0);b&=31;return a<this.tb.a.length?this.tb.a[a].a[c].a[d].a[e].a[b]:c<this.wb.a.length?this.wb.a[c].a[d].a[e].a[b]:d<this.vb.a.length?this.vb.a[d].a[e].a[b]:e<this.ub.a.length?this.ub.a[e].a[b]:this.q.a[b]}return a>=this.Hc?(b=a-this.Hc|0,this.Yb.a[b>>>15|0].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b]):a>=this.Gc?(b=a-this.Gc|0,this.Xb.a[b>>>10|0].a[31&(b>>>5|0)].a[31&b]):
a>=this.Fc?(b=a-this.Fc|0,this.Wb.a[b>>>5|0].a[31&b]):this.j.a[a]}throw this.y(a);};Cd.prototype.da=function(){return 9};Cd.prototype.ea=function(a){switch(a){case 0:return this.j;case 1:return this.Wb;case 2:return this.Xb;case 3:return this.Yb;case 4:return this.tb;case 5:return this.wb;case 6:return this.vb;case 7:return this.ub;case 8:return this.q;default:throw new U(a);}};Cd.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.p))throw this.y(a);};
H(Cd,"scala.collection.immutable.Vector5",{Le:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});function Dd(a,b,c,d,e,f,h,l,q,w,A,x,C,v,u,M,va){this.q=this.j=null;this.p=0;this.Jc=b;this.Zb=c;this.Kc=d;this.$b=e;this.Lc=f;this.ac=h;this.Mc=l;this.bc=q;this.Nc=w;this.xb=A;this.Bb=x;this.Ab=C;this.zb=v;this.yb=u;cf(this,a,M,va)}Dd.prototype=new df;Dd.prototype.constructor=Dd;
Dd.prototype.s=function(a){if(0<=a&&a<this.p){var b=a-this.Nc|0;if(0<=b){a=b>>>25|0;var c=31&(b>>>20|0),d=31&(b>>>15|0),e=31&(b>>>10|0),f=31&(b>>>5|0);b&=31;return a<this.xb.a.length?this.xb.a[a].a[c].a[d].a[e].a[f].a[b]:c<this.Bb.a.length?this.Bb.a[c].a[d].a[e].a[f].a[b]:d<this.Ab.a.length?this.Ab.a[d].a[e].a[f].a[b]:e<this.zb.a.length?this.zb.a[e].a[f].a[b]:f<this.yb.a.length?this.yb.a[f].a[b]:this.q.a[b]}return a>=this.Mc?(b=a-this.Mc|0,this.bc.a[b>>>20|0].a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&
(b>>>5|0)].a[31&b]):a>=this.Lc?(b=a-this.Lc|0,this.ac.a[b>>>15|0].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b]):a>=this.Kc?(b=a-this.Kc|0,this.$b.a[b>>>10|0].a[31&(b>>>5|0)].a[31&b]):a>=this.Jc?(b=a-this.Jc|0,this.Zb.a[b>>>5|0].a[31&b]):this.j.a[a]}throw this.y(a);};Dd.prototype.da=function(){return 11};
Dd.prototype.ea=function(a){switch(a){case 0:return this.j;case 1:return this.Zb;case 2:return this.$b;case 3:return this.ac;case 4:return this.bc;case 5:return this.xb;case 6:return this.Bb;case 7:return this.Ab;case 8:return this.zb;case 9:return this.yb;case 10:return this.q;default:throw new U(a);}};Dd.prototype.G=function(a){a|=0;if(!(0<=a&&a<this.p))throw this.y(a);};
H(Dd,"scala.collection.immutable.Vector6",{Me:1,Ja:1,xa:1,wa:1,ia:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,ka:1,ba:1,la:1,qa:1,Y:1,Z:1,ua:1,ma:1,aa:1,$:1,ha:1,c:1});function Vd(){var a=new jf;a.E=Cb(new zb);return a}function jf(){this.E=null}jf.prototype=new Ve;jf.prototype.constructor=jf;g=jf.prototype;g.Oa=function(){return"IndexedSeq"};g.B=function(){return new Kd(new Re(this))};g.Eb=function(a){qc(this,a)};g.z=function(){return this.E.z()};g.J=function(){return this.E.z()};
function kf(a,b){a=a.E;b=""+String.fromCharCode(b);a.o+=b}function lf(a,b){a=a.E;a.o=""+a.o+b}g.C=function(){return this.E.o};g.Kb=function(){return this.E.o};g.Fb=function(a){kf(this,null===a?0:a.Ra)};g.G=function(a){this.E.o.charCodeAt(a|0)};g.s=function(a){return new k(this.E.o.charCodeAt(a))};H(jf,"scala.collection.mutable.StringBuilder",{Ue:1,ld:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,rd:1,pd:1,sd:1,md:1,Za:1,qd:1,Oc:1,Qc:1,Pc:1,nd:1,Y:1,Z:1,od:1,hc:1,c:1});
function Gd(){this.ya=null}Gd.prototype=new Xe;Gd.prototype.constructor=Gd;g=Gd.prototype;g.Oa=function(){return"IndexedSeq"};g.B=function(){return new Kd(new Re(this))};g.s=function(a){return this.ya[a]};g.z=function(){return this.ya.length|0};g.J=function(){return this.ya.length|0};g.Da=function(){return"WrappedArray"};g.Kb=function(){return this};g.Fb=function(a){this.ya.push(a)};g.G=function(){};
H(Gd,"scala.scalajs.js.WrappedArray",{We:1,Pe:1,ld:1,T:1,L:1,M:1,w:1,O:1,x:1,N:1,U:1,S:1,F:1,P:1,K:1,rd:1,pd:1,sd:1,md:1,Za:1,Qe:1,Qc:1,Pc:1,Te:1,aa:1,$:1,nd:1,Y:1,Z:1,od:1,Se:1,Oc:1,c:1});ba=new n(0,0);La.Rc=ba;var mf=new (J(da).m)([]);
try{Sa||(Sa=new Ra);var nf=Qb,of=Ub();wc||(wc=new vc);nf(of,mf,0,wc);a:{var pf,qf,rf;L();var sf=process.argv.slice(2),tf;id||(id=new fd);tf=id;var uf=new Gd;uf.ya=sf;rf=hd(tf,uf);if(null!==rf){var vf=rf.z();if(0===(2===vf?0:2>vf?-1:1)){pf=rf.s(0);qf=rf.s(1);break a}}throw new U(rf);}var wf=pf,xf=qf,yf;L();try{L().za.accessSync(wf,L().za.constants.R_OK),yf=!0}catch(a){if((a instanceof jc?a:new ic(a))instanceof Ac)yf=!1;else throw a;}yf||(Od("'"+wf+"' not readable"),Qa());Pd(oc(),"reading '"+wf+"' ...\n");
var zf=Oa(L(),wf),Af;Af=null;for(var Bf=Vd(),Cf=new Db(zf,!0);Cf.t<Cf.pa;){var Df=Eb(Cf),S=Hd(Df);if(""!==S)if(S.startsWith(";")){var Ef=Hd(Fb());Pd(oc(),"  "+(null===Af?"":"  ")+'comment "'+Ef+'"\n');lf(Bf,yb(R(),Hd("\n           |\n           |+++++ COMMENT: "+Ef+" +++++\n           |")))}else if(S.startsWith("#")){var dg=Hd(Fb());Pd(oc(),"  "+(null===Af?"":"  ")+'section "'+dg+'"\n');lf(Bf,yb(R(),Hd("\n           |\n           |+++++ SECTION: "+dg+" +++++\n           |")))}else if(S.startsWith("/")||
S.startsWith("./")||S.startsWith("../")){var eg;if(S.endsWith("/")){R();var fg=S;R();var gg=fg.length-1|0;R();var hg=fg.length;eg=xb(fg,0,gg<hg?gg:hg)}else eg=S;Pd(oc(),"  path: "+eg+"\n");Af=S;lf(Bf,yb(R(),Hd("\n           |\n           |+++++ FOLDER: "+Af+" +++++\n           |")))}else{null===Af&&(Od("can't include '"+S+"' because a path hasn't been set"),Qa());Pd(oc(),"    including '"+S+"'\n");var ig=Oa(L(),Af+"/"+S);lf(Bf,yb(R(),Hd("\n           |\n           |+++++ FILE: "+S+" +++++\n           |")));
lf(Bf,ig);lf(Bf,yb(R(),Hd("\n           |+++++ END FILE +++++\n           |")));ig.endsWith("\n")||kf(Bf,10)}}Pd(oc(),"writing '"+xf+"' ...\n");L();var jg=Bf.E.o;L().za.writeFileSync(xf,jg)}catch(a){if(a instanceof Wc)Ub(),Pd(oc(),"Illegal command line"+(0===a.Mb?"":1===a.Mb?" after first argument":" after "+a.Mb+" arguments")+": "+a.$c+"\n");else throw a;};
}).call(this);
//# sourceMappingURL=main.js.map
